; ENTRY POINT FROM GRUB AND THE C KERNEL IN ASSEMBLY FOR THE "BaseKernel" X86 OPERATING SYSTEM FROM SCRATCH - https://github.com/Huguini79/BaseKernel

BITS 32 ; DEFINE THE BITS (32 BITS)

SECTION .multiboot ; DEFINE TEXT THE SECTION (FOR THE REST OF THE CODE)

; DEFINE THE MULTIBOOT HEADERS
ALIGN 4
DD 0x1BADB002
DD 0x00
DD - (0x1BADB002 + 0x00)

SECTION .text

GLOBAL START ; START OF THE KERNEL (ESSENTIAL FOR THE LINKER)
EXTERN kernel_main ; OUR C FUNCTIONS THAT JUMPS TO THE C KERNEL

START:
	CLI ; DISABLE INTERRUPTS
	CALL kernel_main ; JUMP INTO THE C KERNEL
	HLT ; PUT THE DISK IN STANDBY MODE

SECTION .bss ; DEFINE THE BSS SECTION (FOR THE STACK)

STACK_SPACE: RESB 128000 ; 128 KB OF STACK
