; I/O IMPLEMENTATION FROM SCRATCH FOR THE "BaseKernel" X86 OPERATING SYSTEM FROM SCRATCH - https://github.com/Huguini79/BaseKernel

; DEFINE THE FUNCTIONS
GLOBAL insb
GLOBAL insw
GLOBAL outb
GLOBAL outw

; DEFINE THE INSB FUNCTION
insb:
	PUSH EBP ; MOVE THE EBP REGISTER INTO THE STACK
	MOV EBP, ESP ; COPY THE STACK INTO THE EBP REGISTER

	XOR EAX, EAX ; CLEAN THE EAX REGISTER (RECOMMENDED)
	MOV EDX, [EBP + 8] ; MOVE INTO THE EDX REGISTER 8 BYTES OF OFFSET OF THE EBP REGISTER (THIS CONTAINS THE I/O ADDRESS THAT WE PUT FROM C)
	IN AL, DX ; FINALLY, WE READ FROM THE I/O PORT THAT WE PUT IN OUR C CODE, THE DX REGISTER IS A SMALL PART OF THE EDX REGISTER

	POP EBP ; DELETE THE EBP REGISTER FROM THE STACK
	RET ; FINALLY, WE GET OUT OF THIS FUNCTION

; DEFINE THE INSW FUNCTION
insw:
        PUSH EBP ; MOVE THE EBP REGISTER INTO THE STACK
        MOV EBP, ESP ; COPY THE STACK INTO THE EBP REGISTER

        XOR EAX, EAX ; CLEAN THE EAX REGISTER (RECOMMENDED)
        MOV EDX, [EBP + 8] ; MOVE INTO THE EDX REGISTER 8 BYTES OF OFFSET OF THE EBP REGISTER (THIS CONTAINS OUT I/O PORT THAT WE SEND FROM C
        IN AX, DX ; FINALLY, WE READ FROM THE I/O PORT THAT WE PUT IN OUR C CODE, THE DX REGISTER IS A SMAL>

        POP EBP ; DELETE THE EBP REGISTER FROM THE STACK
        RET ; FINALLY, WE GET OUT OF THIS FUNCTION

; DEFINE THE OUTB FUNCTION
outb:
	PUSH EBP ; MOVE THE EBP REGISTER INTO THE STACK
	MOV EBP, ESP ; COPY THE STACK INTO THE EBP REGISTER

	XOR EAX, EAX ; CLEAN THE EAX REGISTER (RECOMMENDED)
	MOV EAX, [EBP + 12] ; MOVE INTO THE EAX REGISTER 12 BYTES OF THE OFFSET OF THE EBP REGISTER (THIS CONTAINS THE VAL OF THAT WE WANT TO PUT IN THE I/O PORT
	MOV EDX, [EBP + 8] ; MOVE INTO THE EDX REGISTER 8 BYTES OF THE OFFSET OF THE EBP REGISTER (THIS CONTAINS OUR I/O PORT THAT WE SEND FROM C)
	OUT DX, AL ; FINALLY, WE SENT THE DATA(VAL) TO THE I/O PORT

	POP EBP ; DELETE THE EBP REGISTER FROM THE STACK
	RET ; FINALLY, WE GET OUT OF THIS FUNCTION

; DEFINE THE OUTW FUNCTION
outw:
        PUSH EBP ; MOVE THE EBP REGISTER INTO THE STACK
        MOV EBP, ESP ; COPY THE STACK INTO THE EBP REGISTER

        XOR EAX, EAX ; CLEAN THE EAX REGISTER (RECOMMENDED)
        MOV EAX, [EBP + 12] ; MOVE INTO THE EAX REGISTER 12 BYTES OF THE OFFSET OF THE EBP REGISTER (THIS C>
        MOV EDX, [EBP + 8] ; MOVE INTO THE EDX REGISTER 8 BYTES OF THE OFFSET OF THE EBP REGISTER (THIS CON>
        OUT DX, AX ; FINALLY, WE SENT THE DATA(VAL) TO THE I/O PORT

        POP EBP ; DELETE THE EBP REGISTER FROM THE STACK
        RET ; FINALLY, WE GET OUT OF THIS FUNCTION
