// CONFIG HEADER FILE FOR THE "BaseKernel" X86 OPERATING SYSTEM FROM SCRATCH - https://github.com/Huguini79/BaseKernel
#ifndef CONFIG_H
#define CONFIG_H

// TOTAL GDT SEGMENTS - (NULL SEGMENT, KERNEL CODE, KERNEL DATA)
#define BASEKERNEL_TOTAL_GDT_SEGMENTS 3

#endif
