// VGA HEADER FILE FOR THE "BaseKernel" X86 OPERATING SYSTEM FROM SCRATCH - https://github.com/Huguini79/BaseKernel
#ifndef VGA_H
#define VGA_H

// 80X25 VGA TEXT MODE
#define VGA_WIDTH 80
#define VGA_HEIGHT 25

// IMPORT THE LIBRARIES THAT WE NEED
#include <stdint.h>
#include <stddef.h>

// #include "string.h"

// DEFINE THE VGA STRUCT

struct vga {
	uint16_t* video_mem; // VIDEO MEM -> 0xB8000 ------ vga->video_mem = (uint16_t*)(0xB8000);
	uint16_t row; // ROW (Y POSITION)
	uint16_t col; // COL (X POSITION)
};

// DEFINE ALL THE VGA FUNCTIONS
void init_screen(); // INIT_SCREEN FUNCTION (WE INITIALIZE THE SCREEN FROM THE 0xB8000 address
void panic(const char* error); // PANIC FUNCTION (WE USE IT ON OUR KEYBOARD DRIVER)
void overwrite(); // OVERWRITE FUNCTION (WE USE IT IN OUR KEYBOARD DRIVER)
void perfectchar2(char c, char color); // PERFECTCHAR2 (SPECIAL FUNCTION THAT WE CALL IT IN OUR KEYBOARD DRIVER)
void row_plus(); // ROW_PLUS FUNCTION (WE CALL THIS IN OUR C KERNEL)
void backspace_vga(); // BACKSPACE_VGA FUNCTION (WE CALL THIS IN OUR KEYBOARD DRIVER FOR THE BACKSPACE KEY)
void go_left(); // GO_LEFT FUNCTION (WE USE THIS FUNCTION IN THE KEYBOARD DRIVER)
void go_right(); // GO_RIGHT FUNCTION (WE USE THIS FUNCTION IN THE KEYBOARD DRIVER)
void go_up(); // GO_UP FUNCTION (WE USE THIS FUNCTION IN THE KEYBOARD DRIVER)
void go_down(); // GO_DOWN FUNCTION (WE USE THIS FUNCTION IN THE KEYBOARD DRIVER)
void xychar(int x, int y, char c, char color); // DEFINE THE XYCHAR FUNTION (WE PUT CARACTERS IN THE VIDEO MEM ------ vga->video_mem[(y * VGA_WIDTH) + x] = (uint16_t)(color << 8) | c;
void perfectchar(char c, char color); // DEFINE THE PERFETCHAR FUNCTION (WE PUT CARACTERS IN THE VIDEO MEM WITHOUT PUTTING THE X AND Y POSITION THAT WE WANT TO PUT, BECAUSE IN THIS FUNCTION WE AUTOMATICALLY INCREMENT THE "vga->col" AND "vga->row" POSITION, SO WE DON'T HAVE TO PUT MANUALLY
void printb(const char* str); // DEFINE THE PRINTB FUNCTION (WE USE THE PERFECTCHAR FUNCTION TO PUT THE CHARACTERES AUTOMATICALLY, BUT PRINTB AUTOMATICALLY PUTS LONGER TEXT USING THE STRLEN() FUNCTION(FROM THE "STRING.H" LIBRARY)
void clear(); // DEFINE THE CLEAR FUNCTION (WE USE THIS TO CLEAR THE SCREEN OR TO PREPARE THE SCREEN TO WRITE)

#endif
